### ISSUE TITLE
Setup Nvidia GPUs in ARC Runner for GPU nodetypes

### ISSUE THREAD

**Issue by zxiiro** [pytorch/ci-infra#75]
In order for runner scale sets to request GPUs for the ARC runners. We need to add a resource limit and/or request to the container `runner` template.

```
    containers:
    - name: runner
      image: ghcr.io/pytorch/arc-runner-pytorch:$(LATESTRUNNERIMG)
      command: ["/home/runner/run.sh"]
      resources:
        limits:
          cpu: $(CPU)
          memory: $(MEMORY)
          nvidia.com/gpu: 1
        requests:
          cpu: $(CPU)
          memory: $(MEMORY)
          nvidia.com/gpu: 1
...
```

This needs to be added once the GPU hosts are properly setup to provide Nvidia GPUs.
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/ci-infra/issues/77
- [ ] https://github.com/pytorch/ci-infra/issues/76
- [ ] https://github.com/pytorch/ci-infra/issues/74
```
